server:
  port: 8764

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/restaurant-service-db
    username: root
    password: password
  jpa: 
    hibernate: 
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL55Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
